// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_test1
void rcpp_test1(const Rcpp::DataFrame df);
RcppExport SEXP _junk_rcpp_test1(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type df(dfSEXP);
    rcpp_test1(df);
    return R_NilValue;
END_RCPP
}
// rcpp_test2
void rcpp_test2(const Rcpp::DataFrame df);
RcppExport SEXP _junk_rcpp_test2(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type df(dfSEXP);
    rcpp_test2(df);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_junk_rcpp_test1", (DL_FUNC) &_junk_rcpp_test1, 1},
    {"_junk_rcpp_test2", (DL_FUNC) &_junk_rcpp_test2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_junk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
